In [73]:
# impor dataset, name it as df
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("used_cars.csv")
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [74]:
# Dataset information

# Varible name and date type
for column in df.columns:
  print(f"{column}: {df[column].dtype}")

# Shape
df.shape

brand: object
model: object
model_year: int64
milage: object
fuel_type: object
engine: object
transmission: object
ext_col: object
int_col: object
accident: object
clean_title: object
price: object

(4009, 12)

In [75]:
# Numeric variables
from matplotlib.ticker import MaxNLocator
import re

# "milage"
df['milage'] = df['milage'].str.replace(r'\D', '', regex=True)
df['milage'] = df['milage'].astype(int)

# "price"
df['price'] = df['price'].str.replace(',', '', regex=True)
df['price'] = df['price'].str.replace(r'\$', '', regex=True)
df['price'] = df['price'].astype(int)

df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300
1,Hyundai,Palisade SEL,2021,34742,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999

In [76]:
# Check cardinality for all categorical varibles (before input missing values)
categorical_columns = df.select_dtypes(include=['object']).columns
cardinality = {column: df[column].nunique() for column in categorical_columns}
threshold = 0.01 * len(df)
high_cardinality_cols = {col: count for col, count in cardinality.items() if count > threshold}
high_cardinality_cols

{'brand': 57,
 'model': 1898,
 'engine': 1146,
 'transmission': 62,
 'ext_col': 319,
 'int_col': 156}

In [77]:
# Handling missing values
missing_values = df.isnull().sum()
missing_values

# fuel_type
df['fuel_type'] = df['fuel_type'].fillna('Unknown') # treating missing fuel_type entries as "Unknown" maintains the categorical nature

# accident
np.random.seed(170)
df['accident'] = df['accident'].replace({'None reported': 'no'}) # normalized varible
df['accident'] = df['accident'].replace({'At least 1 accident or damage reported': 'yes'})
accident_missing_entry = df['accident'].isnull()
accident_random_choices = np.random.choice(['yes', 'no'], size=accident_missing_entry.sum())
df.loc[accident_missing_entry, 'accident'] = accident_random_choices  # Fill in missing values with random generate value 'yes' or 'no

# clean_title
df['clean_title'] = df['clean_title'].str.lower()
df['clean_title'] = df['clean_title'].replace({'accident or damage reported': 'no'}) # normalized varible
title_missing_entry = df['clean_title'].isnull()
title_random_choices = np.random.choice(['yes', 'no'], size=title_missing_entry.sum())
df.loc[title_missing_entry, 'clean_title'] = title_random_choices  # Fill in missing values with random generate value 'yes' or 'no
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,yes,yes,10300
1,Hyundai,Palisade SEL,2021,34742,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,yes,yes,38005
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,no,yes,54598
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,no,yes,15500
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,no,yes,34999

In [78]:
# Check for missing value again
missing_values = df.isnull().sum()
missing_values

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [79]:
# Check cardinality (after handling missing values)
categorical_columns = df.select_dtypes(include=['object']).columns
cardinality = {column: df[column].nunique() for column in categorical_columns}
threshold = 0.01 * len(df)
high_cardinality_cols = {col: count for col, count in cardinality.items() if count > threshold}
high_cardinality_cols
# still the same variables that have high cardinality, handled missing values did not impact this

{'brand': 57,
 'model': 1898,
 'engine': 1146,
 'transmission': 62,
 'ext_col': 319,
 'int_col': 156}

In [67]:
X = df.drop(columns="price")
y = df["price"]
print(y)

0        10300
1        38005
2        54598
3        15500
4        34999
         ...
4004    349950
4005     53900
4006     90998
4007     62999
4008     40000
Name: price, Length: 4009, dtype: int64